# Generated by Django 3.1.6 on 2021-02-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_auto_20210224_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='adminside.agent'),
        ),
    ]
